version: '3.5'

services:
  school-guardian-backend:
    container_name: school-guardian-backend
    image: gabrielsoaresdev/school-guardian-backend:latest
    restart: always
    env_file:
      - stack.env
    ports:
      - '3335:3335'
    networks:
      - proxy-reverse-network
      - school-guardian-network
      - postgres-network
    volumes:
      - uploads-school-guardian-volume:/tmp/uploads
networks:
  school-guardian-network:
    name: school-guardian-network
    external: true
  proxy-reverse-network:
    name: proxy-reverse-network
    external: true
  postgres-network:
    name: postgres-network
    external: true
