ARG NODE_IMAGE=node:16.17-alpine


FROM $NODE_IMAGE AS base

RUN apk --no-cache add dumb-init

RUN mkdir -p /app/school-guardian-backend && chown node:node /app/school-guardian-backend
WORKDIR /app/school-guardian-backend

USER node

RUN mkdir tmp

FROM base AS dependencies

COPY --chown=node:node ./package*.json ./

RUN npm ci

COPY --chown=node:node . .

FROM dependencies AS build

RUN  node ace build --production

# RUN  cp -a docs/ build/docs
FROM base AS production

COPY --chown=node:node ./package*.json ./

RUN mkdir -p /app/school-guardian-backend/tmp/uploads/courses && \
  chown -R node:node /app/school-guardian-backend/tmp/uploads/courses

RUN mkdir -p /app/school-guardian-backend/tmp/uploads/academic-papers && \
  chown -R node:node /app/school-guardian-backend/tmp/uploads/academic-papers

RUN mkdir -p /app/school-guardian-backend/tmp/uploads/ortographic-correction/originals && \
  chown -R node:node /app/school-guardian-backend/tmp/uploads/ortographic-correction/originals


RUN mkdir -p /app/school-guardian-backend/tmp/uploads/ortographic-correction/results && \
  chown -R node:node /app/school-guardian-backend/tmp/uploads/ortographic-correction/results

RUN npm ci --production
COPY --chown=node:node --from=build /app/school-guardian-backend/build .


CMD node ace scheduler:run


