name: CI
on:
  pull_request:
    branches:
      - production
      - development
jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: SchoolGuardian-test
          POSTGRES_PASSWORD: XWkIaeExxDmRwdm
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
      redis:
        image: bitnami/redis:latest
        env:
          REDIS_PASSWORD: password
        ports:
          - 6379:6379
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm i
      - name: Install Production Dependencies
        run: npm ci
      - name: Checking types
        run: node ace type-check
      - name: Format code
        run: npm run format
      - name: Verify errors eslint
        run: npm run lint
      - name: Running tests
        run: node ace test
        # redis:
        #   image: bitnami/redis:latest
        #   env:
        #    - REDIS_PASSWORD=password
        #   ports:
        #    - 6379:6379